### 1. Introduciton of pandas

In [1]:
# importing pandas
import pandas as pd

#### 1.1 Popular easy-to-use structure with pandas: Series and DataFrame

In [2]:
##1 create a pandas series
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [3]:
##2 create a pandas dataframe
data = {
    'Name': ['Alice', 'Tim', 'Nathan', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0   Alice   25   50000
1     Tim   30   60000
2  Nathan   35   70000
3   David   40   80000
4     Eva   45   90000


#### 1.2 Basic DataFrame Operations

In [4]:
##1 view the dataframe
print("top 2 rows of dataframe df are: ")
print(df.head(2))
print('\n')
print("bottom 2 rows of dataframe df are: ")
print(df.tail(2))
print('\n')
print("randomly grabbed 2 rows from dataframe df")
print(df.sample(2))

top 2 rows of dataframe df are: 
    Name  Age  Salary
0  Alice   25   50000
1    Tim   30   60000


bottom 2 rows of dataframe df are: 
    Name  Age  Salary
3  David   40   80000
4    Eva   45   90000


randomly grabbed 2 rows from dataframe df
    Name  Age  Salary
3  David   40   80000
1    Tim   30   60000


In [5]:
##2 dispaly a summary of the dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Salary  5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes
None


In [6]:
##3 get a descriptive statistic of the dataframe
print(df.describe())

             Age        Salary
count   5.000000      5.000000
mean   35.000000  70000.000000
std     7.905694  15811.388301
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  70000.000000
75%    40.000000  80000.000000
max    45.000000  90000.000000


In [7]:
##4 access a column or multiple columns
print("accessing a column")
print(df['Name'])
print('\n')
print("accesing multiple columns")
print(df[['Name','Age']])

accessing a column
0     Alice
1       Tim
2    Nathan
3     David
4       Eva
Name: Name, dtype: object


accesing multiple columns
     Name  Age
0   Alice   25
1     Tim   30
2  Nathan   35
3   David   40
4     Eva   45


In [8]:
##5 access a row or multiple rows
print("accessing first row of dataframe df")
print(df.iloc[0])
print('\n')
print("accessing first and third rows of dataframe df")
print(df.iloc[[0,2]])
print('\n')
print("accessing first to third rows of dataframe df")
print(df.iloc[0:2])

accessing first row of dataframe df
Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object


accessing first and third rows of dataframe df
     Name  Age  Salary
0   Alice   25   50000
2  Nathan   35   70000


accessing first to third rows of dataframe df
    Name  Age  Salary
0  Alice   25   50000
1    Tim   30   60000


In [9]:
##6 filter data 
print("Filter people elder than 30")
print(df[df['Age'] > 30]) 

Filter people elder than 30
     Name  Age  Salary
2  Nathan   35   70000
3   David   40   80000
4     Eva   45   90000


In [10]:
##7 add a new column and delete a column
### adding a column called "Bonus" which is 12.5% of the salary
df['Bonus'] = df['Salary'] * 0.1
print("data frame aftering adding a column: ")
print(df)
print('\n')

### deleting the newly added column "Bonus"
print("data frame aftering deleting the enwly added column: ")
print(df.drop(columns=['Bonus']))

data frame aftering adding a column: 
     Name  Age  Salary   Bonus
0   Alice   25   50000  5000.0
1     Tim   30   60000  6000.0
2  Nathan   35   70000  7000.0
3   David   40   80000  8000.0
4     Eva   45   90000  9000.0


data frame aftering deleting the enwly added column: 
     Name  Age  Salary
0   Alice   25   50000
1     Tim   30   60000
2  Nathan   35   70000
3   David   40   80000
4     Eva   45   90000


### 2 Introduction of NumPy

In [11]:
# importing NumPy
import numpy as np

#### 2.1 Creating NumPy Arrays

In [12]:
##1 creating a 1D array
arr_1d_1 = np.array([1, 2, 3, 4, 5])
print("The 1d array example looks like")
print(arr_1d_1)
print('\n')
##2 creating a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The 2d array example looks like")
print(arr_2d)

The 1d array example looks like
[1 2 3 4 5]


The 2d array example looks like
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
##3 using arange() (creates arrays with evenly spaced values)
arr_1d_2 = np.arange(0, 10, 2) # 0 and 10 denote the range, while 2 referrs to the space or step
print("The 1d array example created with arrange() is: ")
print(arr_1d_2)

The 1d array example created with arrange() is: 
[0 2 4 6 8]


In [14]:
##4 creating a arrary with all zero or one
arr_1d_3 = np.zeros(5)
print("all zero array with zeros()")
print(arr_1d_3)
print('\n')
arr_1d_4 = np.ones(5)
print("all one array with ones()")
print(arr_1d_4)

all zero array with zeros()
[0. 0. 0. 0. 0.]


all one array with ones()
[1. 1. 1. 1. 1.]


In [15]:
##5 using linspace() (creates arrays with a specified number of evenly spaced values)
arr_1d_5 = np.linspace(0, 1, 5) # 0 and 1 define the range, while 5 denotes the number of elements created with even split of the range
print("The 1d array crated with linspace()")
print(arr_1d_5)

The 1d array crated with linspace()
[0.   0.25 0.5  0.75 1.  ]


#### 2.2 Basic Array Operations

In [16]:
##1 array shape and reshaping
matrix_1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array shape")
print(matrix_1.shape)
print("Original array")
print(matrix_1)
print('\n')

matrix_1_resahpe = matrix_1.reshape((3, 2))
print("The array shape after reshaped")
print(matrix_1_resahpe.shape)
print("The array shape after reshaped")
print(matrix_1_resahpe)

Original array shape
(2, 3)
Original array
[[1 2 3]
 [4 5 6]]


The array shape after reshaped
(3, 2)
The array shape after reshaped
[[1 2]
 [3 4]
 [5 6]]


In [17]:
##2 array indexing and slicing for 1d array
print("Here uses arr_1d_1 created earlier to show the operations:")
print("arr_1d_1:", arr_1d_1)
print('\n')
print("The second elemen in arr_1d_1 is")
print(arr_1d_1[1])
print("Here is the sliced elements from index 1 to 2")
print(arr_1d_1[1:3])

Here uses arr_1d_1 created earlier to show the operations:
arr_1d_1: [1 2 3 4 5]


The second elemen in arr_1d_1 is
2
Here is the sliced elements from index 1 to 2
[2 3]


In [18]:
##3 array indexing and slicing for 2d array
print("Here uses matrix_1 created earlier to show the operations:")
print("matrix_1:", matrix_1)
print('\n')
print("The elemen at 1st row and 2nd column in matrix_1 is")
print(matrix_1[0][1])
print("Here is the sliced elements from row 1, and column 1 to 2")
print(matrix_1[0][0:2])

Here uses matrix_1 created earlier to show the operations:
matrix_1: [[1 2 3]
 [4 5 6]]


The elemen at 1st row and 2nd column in matrix_1 is
2
Here is the sliced elements from row 1, and column 1 to 2
[1 2]


In [19]:
##4 mathematical operations: Addition, Subtraction, Multiplication, Division
print("Here uses arr_1d_1 created earlier to show the operations:")
print("arr_1d_1:", arr_1d_1)
print('\n')
print("array after adding 20 to each element")
print(arr_1d_1+20)
print('\n')
print("array after mutiplying 5 to each element")
print(arr_1d_1*5)

Here uses arr_1d_1 created earlier to show the operations:
arr_1d_1: [1 2 3 4 5]


array after adding 20 to each element
[21 22 23 24 25]


array after mutiplying 5 to each element
[ 5 10 15 20 25]


In [20]:
##5 mathematical operations: element-wise operations between arrays
print("Here uses arr_1d_1 and arr_1d_2 created earlier to show the operations:")
print("arr_1d_1:", arr_1d_1)
print("arr_1d_2:", arr_1d_2)
print('\n')
print("sum of these 2 arraies arr_1d_1 and arr_1d_2")
print(arr_1d_1+arr_1d_2)

Here uses arr_1d_1 and arr_1d_2 created earlier to show the operations:
arr_1d_1: [1 2 3 4 5]
arr_1d_2: [0 2 4 6 8]


sum of these 2 arraies arr_1d_1 and arr_1d_2
[ 1  4  7 10 13]


In [21]:
##6 mathematical operations: 1d-array-wise operations 
print("Here uses arr_1d_1 created earlier to show the operations:")
print("arr_1d_1:", arr_1d_1)
print('\n')
print('Sum of all the elements in arr_1d_1')
print(arr_1d_1.sum())
print('\n')
print('Mean of all the elements in arr_1d_1')
print(arr_1d_1.mean())
print('\n')
print('Standard Deviation of all the elements in arr_1d_1')
print(arr_1d_1.std())
print('\n')
print('Minimum value of all the elements in arr_1d_1')
print(arr_1d_1.min())
print('\n')
print('Maximum value of all the elements in arr_1d_1')
print(arr_1d_1.max())

Here uses arr_1d_1 created earlier to show the operations:
arr_1d_1: [1 2 3 4 5]


Sum of all the elements in arr_1d_1
15


Mean of all the elements in arr_1d_1
3.0


Standard Deviation of all the elements in arr_1d_1
1.4142135623730951


Minimum value of all the elements in arr_1d_1
1


Maximum value of all the elements in arr_1d_1
5


In [22]:
##7 mathematical operations: 2d-array-wise operations 
print("Here uses matrix_1 created earlier to show the operations:")
print("matrix_1:", matrix_1)
print('\n')

print("Sum of all the elements in matrix_1")
print(matrix_1.sum())
print('\n')
print("Sum of each column in matrix_1")
print(matrix_1.sum(axis=0))
print('\n')
print("Sum of each row in matrix_1")
print(matrix_1.sum(axis=1))
print('\n')

print('Minimum value of all the elements in matrix_1')
print(matrix_1.min())
print('\n')
print("Minimum value of each column in matrix_1")
print(matrix_1.min(axis=0))
print('\n')
print("Minimum value of each row in matrix_1")
print(matrix_1.min(axis=1))

Here uses matrix_1 created earlier to show the operations:
matrix_1: [[1 2 3]
 [4 5 6]]


Sum of all the elements in matrix_1
21


Sum of each column in matrix_1
[5 7 9]


Sum of each row in matrix_1
[ 6 15]


Minimum value of all the elements in matrix_1
1


Minimum value of each column in matrix_1
[1 2 3]


Minimum value of each row in matrix_1
[1 4]


In [23]:
##8 array transposing and flattening
print("Here uses matrix_1 created earlier to show the operations:")
print("matrix_1:", matrix_1)
print('\n')

print("matrix_1 after transporting")
print(matrix_1.T)
print('\n')

print("matrix_1 after flattening")
print(matrix_1.flatten())

Here uses matrix_1 created earlier to show the operations:
matrix_1: [[1 2 3]
 [4 5 6]]


matrix_1 after transporting
[[1 4]
 [2 5]
 [3 6]]


matrix_1 after flattening
[1 2 3 4 5 6]
